In [9]:
import pandas as pd
from pandas.io.html import read_html
from selenium import webdriver
from datetime import datetime

In [17]:
pages = ['https://www.f1fantasytracker.com/sentiment-tracker.html', 'https://www.f1fantasytracker.com/prices.html']
ids = ['constructorTable', 'driverTable']

In [18]:
from webdriver_manager.firefox import GeckoDriverManager

driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())
# driver.get()

====== WebDriver manager ======
Current firefox version is 101.0
Get LATEST geckodriver version for 101.0 firefox
Driver [/Users/michaelmatney/.wdm/drivers/geckodriver/macos/v0.31.0/geckodriver] found in cache

In [19]:
frames = []

for page in pages:
    driver.get(page)
    for id in ids:
        table = driver.find_element_by_id(id)
        data = read_html(table.get_attribute('outerHTML'))
        frames.append(data[0])

In [20]:
driver.close()
driver.quit()

In [21]:
frames[0]

           Team  12 Hour  3 Hour  Latest Sentiment
0      Williams       29     -13     -28       69%
1       Ferrari       46      21       2       46%
2  Aston Martin       27       1       0       27%
3    AlphaTauri        8       1       0       11%
4    Alfa Romeo       -6      -1       0      -26%
5      Mercedes        2       1       0      -27%
6        Alpine        4       1       0      -42%
7       Mclaren        1       0       0      -45%
8      Red Bull      -63     -62      -4      -63%
9          Haas       -2      -1       0      -84%

In [22]:
frames[1]

                                 Driver  12 Hour  3 Hour  Latest Sentiment
0           Sergio Perez  PER  Red Bull       27       7       1       73%
1         Pierre Gasly  GAS  AlphaTauri      -13       1       0       71%
2          Fernando Alonso  ALO  Alpine        6       1       0       63%
3      Valtteri Bottas  BOT  Alfa Romeo       11       0       0       63%
4         George Russell  RUS  Mercedes       16       4       1       57%
5          Guanyu Zhou  ZHO  Alfa Romeo       67       0       0       56%
6         Charles Leclerc  LEC  Ferrari       -9      -3      -1       30%
7            Mick Schumacher  SCH  Haas        0      -1      -1       14%
8            Kevin Magnussen  MAG  Haas        7      -1       0       10%
9        Daniel Ricciardo  RIC  Mclaren        0      -1       0        5%
10        Yuki Tsunoda  TSU  AlphaTauri        3       0       0        0%
11       Nicholas Latifi  LAT  Williams        6       1       0       -7%
12        Max Verstappen  VER  Red Bull       -1       0       0      -17%
13            Esteban Ocon  OCO  Alpine       -7      -1       0      -18%
14           SAI  Carlos Sainz  Ferrari       -8      -2      -1      -29%
15           Lando Norris  NOR  Mclaren       -6      -1       0      -29%
16  Sebastian Vettel  VET  Aston Martin        6       1       0      -54%
17      Lance Stroll  STR  Aston Martin      -62       0       0      -62%
18        Lewis Hamilton  HAM  Mercedes       -1       0       0      -96%
19            Alex Albon  ALB  Williams        0       0       0      -97%

In [23]:
frames[2]

           Team Current Price Season Start PriceSeason Price  Points/Million
0      Mercedes        $33.7m                         $34.5m            1.40
1      Red Bull        $32.4m                         $32.5m            1.98
2       Ferrari        $25.8m                         $25.0m            1.71
3       Mclaren        $17.6m                         $18.5m            1.14
4        Alpine        $13.9m                         $14.0m            1.34
5  Aston Martin        $11.0m                         $11.5m            1.50
6    AlphaTauri        $10.1m                         $10.5m            1.14
7    Alfa Romeo         $8.7m                          $8.0m            1.87
8      Williams         $6.5m                          $7.0m            1.92
9          Haas         $6.4m                          $6.0m            0.68

In [24]:
frames[3]

,Driver,Current Price,Season Start PriceSeason Price,Points/Million
0,Max Verstappen VER Red Bull,$30.5m,$30.5m,1.23
1,Lewis Hamilton HAM Mercedes,$30.1m,$31.0m,0.64
2,George Russell RUS Mercedes,$23.7m,$24.0m,1.31
3,Charles Leclerc LEC Ferrari,$19.0m,$18.0m,1.65
4,Sergio Perez PER Red Bull,$18.2m,$17.5m,1.83
5,SAI Carlos Sainz Ferrari,$17.2m,$17.0m,1.10
6,Lando Norris NOR Mclaren,$15.8m,$16.0m,1.12
7,Daniel Ricciardo RIC Mclaren,$13.5m,$14.5m,0.56
8,Pierre Gasly GAS AlphaTauri,$12.9m,$13.5m,0.82
9,Esteban Ocon OCO Alpine,$12.4m,$12.0m,1.29
10,Fernando Alonso ALO Alpine,$12.2m,$12.5m,0.65
11,Sebastian Vettel VET Aston Martin,$11.4m,$11.5m,0.91
12,Valtteri Bottas BOT Alfa Romeo,$9.6m,$9.0m,2.01
13,Lance Stroll STR Aston Martin,$9.0m,$9.5m,1.26
14,Guanyu Zhou ZHO Alfa Romeo,$8.4m,$8.0m,0.42
15,Yuki Tsunoda TSU AlphaTauri,$8.3m,$8.5m,0.74
16,Alex Albon ALB Williams,$7.8m,$7.5m,1.23
17,Nicholas Latifi LAT Williams,$6.6m,$7.0m,1.23
18,Mick Schumacher SCH Haas,$6.2m,$6.5m,0.42
19,Kevin Magnussen MAG Haas,$6.1m,$5.5m,1.09

In [27]:
driver = frames[1].merge(frames[3], on='Driver')

In [28]:
team = frames[0].merge(frames[2], on='Team')

In [32]:
out = [team, driver]

for frame in out:
    frame['ts'] = (datetime.now()).strftime('%Y-%m-%d %H:%M:%S')

## Write Data

In [15]:
frame_labels = ['team_sent', 'driver_sent']

for i, frame in enumerate(out):
    frame.to_csv(f'./data/raw/sent/{frame_labels[i]}-{datetime.now():%Y-%m-%d.%H%M%S}.csv', sep='|')

OSError: Cannot save file into a non-existent directory: 'data/raw/sent'